### ISSUE TITLE
create toggle for WQP data

### ISSUE THREAD

**Issue by danbernstein** [DataKind-DC/CMC#7]
Right now, the Water Quality Portal (WQP) data is overlayed on the map. I would like to add a toggle that allows the user to show or hide the WQP data. This will allow users who are only interested in seeing CMC data to only see that, while making WQP data available when needed.

**Comment by neilsquinn** [comment]
@danbernstein made an initial commit to a new branch. It's enabled by default, as before.

Thinking we probably want to mess with the styling before we call it done, specifically:
* reduce the font size to be closer to the other controls, and maybe try and shrink the toggle size as well since it's not really the most important UI element and doesn't need so much weight
* put an icon in there for accessibility purposes - right now it looks wonky when you do so (see  [React-Toggle](http://aaronshaf.github.io/react-toggle/) for the docs)
* shift the label slightly to the right so it's not butting up against the toggle

I can try and work on that stuff later before opening a PR, if that sounds good.

**Comment by danbernstein** [comment]
Looks great. Those change sound like good decisions.
